services:
  test_database:
    container_name: analyzeDocDbTest
    image: postgres:16
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: raditz
      POSTGRES_USER: kakarott
      POSTGRES_DB: DBZ