services:
  # api:
  #   container_name: sampleapi
  #   image: sampleapi:latest
  #   ports:
  #     - 127.0.0.1:8000:8000
  #   environment:
  #     DB_URL : jdbc:postgresql://test_database:5432/DBZ
  #     DB_USERNAME : kakarott
  #     DB_PASSWORD : raditz
  #     S3_INVOICE_BUCKET : invocie-reader-bucket
  #     S3_INVOICE_FOLDER : invoices/
  test_database:
    container_name: OCRServiceDb
    image: postgres:16
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: raditz
      POSTGRES_USER: kakarott
      POSTGRES_DB: DBZ