name: Build

on:
  pull_request:
    branches: main

jobs:
    test:
        if: ${{ github.head_ref == 'invoice-reader' }}
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: apps/invoiceReader      
        steps: 
          - uses: actions/checkout@v4

          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              java-version: '17'
              distribution: 'temurin'
              cache: maven

          - name: Build with Maven
            run: mvn -B package --file pom.xml

    build_docker_image:
        needs: test
        uses: markov-ngz/invoice-reader/.github/workflows/build.yaml@main
        permissions:
          id-token: write
          contents: read
        secrets: inherit
        with:
            application_working_directory: apps/invoiceReader
            image_name: ${{ vars.TF_VAR_INVOICEREADER_IMAGE_REGISTRY }} # the tag is set to the commit id 
            image_tag_variable: "invoiceReader_image_tag"
            registry_project: ${{ vars.AWS_PROJECT_ID}}
            registry_location: ${{ vars.AWS_REGION}}
