name: Build

on:
  pull_request:
    branches: main

jobs:
    test:
        if: ${{ github.head_ref == 'invoice-reader' }}
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: apps/invoice-reader      
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4

    build_docker_image:
        needs: test
        uses: markov-ngz/basic-service-template/.github/workflows/build.yaml@main
        permissions:
          id-token: write
          contents: read
        secrets: inherit
        with:
            application_working_directory: apps/invoice-reader
            image_name: ${{ vars.TF_VAR_INVOICEREADER_IMAGE_REGISTRY }} # the tag is set to the commit id 
            image_tag_variable: "invoiceReader_image_tag"
            registry_project: ${{ vars.AWS_PROJECT_ID}}
            registry_location: ${{ vars.AWS_REGION}}
